In [1]:
# Kiểm tra unique bảng essential skill

import pandas as pd

In [5]:
df_software = pd.read_csv("../data/raw/onet/software_skills.csv")

df_software.head()

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,2.E.6.c,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,2.E.2.a,Accounting software,N,N

In [6]:
df_software["Element Name"].unique()

<ArrowStringArray>
[                                         'Document management software',
                           'Data base user interface and query software',
                                             'Content workflow software',
                         'Customer relationship management CRM software',
                                                   'Accounting software',
                                          'Data base reporting software',
                                              'Electronic mail software',
                                              'Time accounting software',
                           'Enterprise application integration software',
                                    'Graphics or photo imaging software',
 ...
                                             'Foreign language software',
                                                        'Spell checkers',
                                    'Text to speech conversion software',
                                                          'Action games',
                                                 'Eye tracking software',
                                               'Contact center software',
                                                          'Fax software',
                                                   'Bar coding software',
 'Computer aided design CAD and computer aided manufacturing CAM system',
                            'Voice synthesizer and recognition software']
Length: 134, dtype: str

# Kiểm tra transferabel

In [7]:
df_transferable = pd.read_csv("../data/raw/onet/transferable_skills.csv")

df_transferable.head()

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.B.1.b,Coordination,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.B.1.b,Coordination,LV,Level,4.88,8,0.2266,4.4309,5.3191,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.B.1.c,Persuasion,IM,Importance,4.00,8,0.1890,3.6296,4.3704,N,NaN,08/2023,Analyst

In [8]:
df_transferable["Element Name"].unique()

<ArrowStringArray>
[            'Social Perceptiveness',                      'Coordination',
                        'Persuasion',                       'Negotiation',
                       'Instructing',               'Service Orientation',
           'Complex Problem Solving',               'Operations Analysis',
                 'Technology Design',               'Equipment Selection',
                      'Installation',                       'Programming',
             'Operations Monitoring',             'Operation and Control',
             'Equipment Maintenance',                   'Troubleshooting',
                         'Repairing',          'Quality Control Analysis',
      'Judgment and Decision Making',                  'Systems Analysis',
                'Systems Evaluation',                   'Time Management',
 'Management of Financial Resources',  'Management of Material Resources',
 'Management of Personnel Resources']
Length: 25, dtype: str